### ISSUE TITLE
enable vue-flux slideshow in new page

### ISSUE THREAD

**Issue by rc-sea** [rc-colabear/slideshow#14]
the current version of vue-flux appears as an overlay on top of the existing browse-view page. can we:

1 load it in a different page OR
2 load it in a bottom sheet that covers the existing browse view

(1 is preferred)

if this issue persists, can we eliminate the slideshow loading 3 images and then the remaining number of images.

**Comment by costibotez** [comment]
I'll make it to load in a different page.

**Comment by costibotez** [comment]
I think back button should be in slide show page too.
