### ISSUE TITLE
tagging multiple photos

### ISSUE THREAD

**Issue by rc-sea** [rc-colabear/slideshow#27]
Hi Costis,

Have you tried tagging multiple photos in. a session?  It seems I can only update one at a time. If I am successful in adding tags on one page but then progress to the next detail page i can't successfully submit. And when I refresh the page (the new detail page), I need to log in again.

Can you verify whether this is something that occurs for you as well?  Are we adding to a global state or somehow weirdly this page?

Thanks!

**Comment by costibotez** [comment]
Sorry for this bug. The bug happens when there were no tags for the photo.
I've fixed it, so please check it again.

**Comment by rc-sea** [comment]
resolved
