### ISSUE TITLE
search results sometimes give weird results

### ISSUE THREAD

**Issue by rc-sea** [rc-colabear/slideshow#28]
If I run this search from the new photo-browse:
https://rememberinglouise.com/photo-browse?search=jane&type=0
i only get 1 result but i make this api call in postman and cloudinary i get multiple responses (and since i tagged "jane" in a bunch of photos...

any idea what's going on?

**Comment by costibotez** [comment]
The existing tag name is "Jane" and you typed "jane" in the search URL.
When I search with the tag "Jane", it shows 11 results.
