### ISSUE TITLE
Responsive view for Photo detail page

### ISSUE THREAD

**Issue by rc-ms** [rc-colabear/slideshow#70]
The display of images on the detail page for smaller displays needs to be changed.  you can see the difference in the first image from the browse page 

<img width="477" alt="Browse_Photos_--_Remembering_Louise_-_mom-slideshow" src="https://user-images.githubusercontent.com/12474675/87216775-a211af00-c2f7-11ea-930c-f67d89c23586.png">

vs. the detail page

<img width="471" alt="Photo_detail_--_Remembering_Louise_-_mom-slideshow_and_SomaFM_Player__Heavyweight_Reggae" src="https://user-images.githubusercontent.com/12474675/87216773-9de59180-c2f7-11ea-92e4-a5438cbf5a59.png">

Right now this is the call to Cloudinary: the image height and width would ideally be smaller for ```sm``` and below devices.   
```
            <cld-image align="center" class="photo-container" :public-id="resource.public_id" secure="true">
              <cld-transformation crop="fit" height="700" width="800" />
              <v-btn class="prev-btn prev-next-btn" @click="onPrev">
                <v-icon x-large>mdi-chevron-left </v-icon>
              </v-btn>
              <v-btn class="next-btn prev-next-btn" @click="onNext">
                <v-icon x-large>mdi-chevron-right </v-icon>
              </v-btn>
            </cld-image>
```
Should we change the call to cloudinary (I would prefer that for download efficiency), or should we encapsulate it better (in a v-card?) so it displays better on the smaller devices?

**Comment by rc-colabear** [comment]
The display of images on the detail page for smaller displays needs to be changed.  you can see the difference in the first image from the browse page 

<img width="471" alt="Photo_detail_--_Remembering_Louise_-_mom-slideshow_and_SomaFM_Player__Heavyweight_Reggae" src="https://user-images.githubusercontent.com/12474675/87216773-9de59180-c2f7-11ea-92e4-a5438cbf5a59.png">

vs. the detail page

<img width="477" alt="Browse_Photos_--_Remembering_Louise_-_mom-slideshow" src="https://user-images.githubusercontent.com/12474675/87216775-a211af00-c2f7-11ea-930c-f67d89c23586.png">

Right now this is the call to Cloudinary: the image height and width is clearly wrong.   
```
            <cld-image align="center" class="photo-container" :public-id="resource.public_id" secure="true">
              <cld-transformation crop="fit" height="700" width="800" />
              <v-btn class="prev-btn prev-next-btn" @click="onPrev">
                <v-icon x-large>mdi-chevron-left </v-icon>
              </v-btn>
              <v-btn class="next-btn prev-next-btn" @click="onNext">
                <v-icon x-large>mdi-chevron-right </v-icon>
              </v-btn>
            </cld-image>
```

Should we change the call to cloudinary (I would prefer that for download efficiency), or should we encapsulate it better so it displays better on the smaller devices?
